version: "3.9"
   
services:

  postgres:
    image: postgres:14.2-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - postgres/service.env
  
  weather-service:
    image: weather:latest
    container_name: weather
    build:
      context: ..
      dockerfile: configs/app/service.Dockerfile
    env_file:
      - app/service.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "10000:8000"
    depends_on:
      - postgres

volumes:
  postgres-volume: